# Generated by Django 5.1.2 on 2024-11-02 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('vehicle_identification_number', models.CharField(max_length=17)),
                ('transmission', models.CharField(max_length=50)),
                ('drive_type', models.CharField(choices=[('REAR_WHEEL_DRIVE', 'RWD'), ('FOUR_WHEEL_DRIVE', '4WD'), ('ALL_WHEEL_DRIVE', 'AWD'), ('FRONT_WHEEL_DRIVE', 'FWD'), ('TWO_WHEEL_DRIVE', '2WD')], max_length=20)),
                ('number_of_doors', models.PositiveIntegerField()),
                ('bed_length', models.FloatField()),
                ('bed_width', models.FloatField()),
                ('bed_height', models.FloatField()),
                ('fuel_type', models.CharField(choices=[('GAS', 'GAS'), ('HYBRID', 'HYBRID'), ('ELECTRIC', 'ELECTRIC'), ('DIESEL', 'DIESEL'), ('ETHANOL', 'ETHANOL')], max_length=20)),
                ('bed_cover', models.CharField(choices=[('OPEN', 'OPEN'), ('CAMPER', 'CAMPER'), ('COVERED', 'COVERED')], max_length=50)),
                ('tire_size', models.CharField(max_length=20)),
                ('tailgate', models.BooleanField()),
                ('navigation_type', models.CharField(max_length=50)),
                ('ball_size', models.CharField(choices=[('ONE_AND_THREE_FOURTHS', '1 3/4"'), ('TWO', '2"'), ('THREE', '3"'), ('PIN_AND_KEY', 'PIN and KEY')], max_length=50)),
                ('tow_capacity', models.IntegerField()),
                ('engine_size', models.CharField(choices=[('THREE_LITER', '3 LITER'), ('FIVE_LITER', '5 LITER'), ('V6', 'V6'), ('V8', 'V8')], max_length=30)),
                ('rear_glass_type', models.CharField(choices=[('SLIDE', 'SLIDE'), ('UP_DOWN', 'UP/DOWN'), ('REMOVABLE', 'REMOVABLE')], max_length=50)),
                ('backseat_type', models.CharField(choices=[('BUCKET_SEAT', 'BUCKET SEAT'), ('FOLD_DOWN', 'FOLD DOWN'), ('BENCH', 'BENCH'), ('SIXTY_FORTY', '60/40')], max_length=50)),
                ('is_backseat_foldable', models.BooleanField()),
                ('front_seat_type', models.CharField(choices=[('BUCKET_SEAT', 'BUCKET SEAT'), ('BENCH', 'BENCH')], max_length=50)),
                ('is_front_seat_foldable', models.BooleanField()),
                ('electrical_features', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DriverTruckTrailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_trailer_lights', models.BooleanField()),
                ('plug_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=20)),
                ('mailing_address', models.TextField()),
                ('mailing_address_two', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('registration_date', models.DateField()),
                ('password', models.CharField(max_length=128)),
                ('user_type', models.CharField(choices=[('CUSTOMER', 'CUSTOMER'), ('DRIVER', 'DRIVER'), ('ADMIN', 'ADMIN')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('policy_name', models.CharField(max_length=200)),
                ('policy_number', models.CharField(max_length=50)),
                ('agent_name', models.CharField(max_length=100)),
                ('agent_phone_number', models.CharField(max_length=20)),
                ('agent_id_number', models.CharField(max_length=50)),
                ('coverage', models.CharField(choices=[('COMPLETE', 'COMPLETE'), ('COLLISION', 'COLLISION'), ('ROADSIDE', 'ROADSIDE'), ('LIABILITY', 'LIABILITY'), ('UNINSURED', 'UNINSURED')], max_length=255)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('policy_period', models.CharField(max_length=50)),
                ('content_coverage', models.TextField()),
                ('lien_holder_name', models.CharField(max_length=100)),
                ('lien_holder_account_number', models.CharField(max_length=50)),
                ('lien_holder_phone_number', models.CharField(max_length=20)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.personalinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_information', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.personalinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_information', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.personalinformation')),
            ],
        ),
    ]
