# Generated by Django 5.1.2 on 2024-11-17 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='deliverytransaction',
            name='delivery_item',
        ),
        migrations.AddField(
            model_name='deliverytransaction',
            name='items_to_be_delivered',
            field=models.ManyToManyField(blank=True, related_name='delivery_transactions', to='api.deliveryitem', verbose_name='Items to be Delivered'),
        ),
        migrations.AlterField(
            model_name='trukituser',
            name='user_type',
            field=models.CharField(choices=[('CUSTOMER', 'CUSTOMER')], max_length=50),
        ),
        migrations.AddField(
            model_name='deliverytransaction',
            name='equipment_needed',
            field=models.ManyToManyField(blank=True, related_name='delivery_transactions', to='api.deliveryequipment', verbose_name='Equipment Needed'),
        ),
        migrations.CreateModel(
            name='DeliveryTransactionEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_equipment', to='api.deliveryequipment')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_equipment', to='api.deliverytransaction')),
            ],
            options={
                'unique_together': {('transaction', 'equipment')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryTransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_items', to='api.deliveryitem')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_items', to='api.deliverytransaction')),
            ],
            options={
                'unique_together': {('transaction', 'item')},
            },
        ),
    ]
